#!/bin/csh
    cat bestsqs.out | tail -n +7 | wc -l >! atom.config
    echo "LATTICE" >>! atom.config
    cat bestsqs.out | cellcvrt -c -sig=9 | tail -n +4 | head -3 >>! atom.config
    echo "POSITION" >>! atom.config
    cat bestsqs.out | cellcvrt -f | tail -n +7 | awk '{element_names[1]="H"; element_names[2]="He"; element_names[3]="Li"; \
            element_names[4]="Be"; element_names[5]="B"; element_names[6]="C"; element_names[7]="N"; element_names[8]="O"; \
            element_names[9]="F"; element_names[10]="Ne"; element_names[11]="Na"; element_names[12]="Mg"; element_names[13]="Al"; \
            element_names[14]="Si"; element_names[15]="P"; element_names[16]="S"; element_names[17]="Cl"; element_names[18]="Ar"; \
            element_names[19]="K"; element_names[20]="Ca"; element_names[21]="Sc"; element_names[22]="Ti";element_names[23]="V"; \
            element_names[24]="Cr"; element_names[25]="Mn"; element_names[26]="Fe"; element_names[27]="Co"; element_names[28]="Ni"; \
            element_names[29]="Cu"; element_names[30]="Zn"; element_names[31]="Ga"; element_names[32]="Ge"; element_names[33]="As"; \
            element_names[34]="Se"; element_names[35]="Br"; element_names[36]="Kr"; element_names[37]="Rb"; element_names[38]="Sr"; \
            element_names[39]="Y"; element_names[40]="Zr"; element_names[41]="Nb"; element_names[42]="Mo"; element_names[43]="Tc"; \
            element_names[44]="Ru"; element_names[45]="Rh"; element_names[46]="Pd"; element_names[47]="Ag"; element_names[48]="Cd"; \
            element_names[49]="In"; element_names[50]="Sn"; element_names[51]="Sb"; element_names[52]="Te"; element_names[53]="I"; \
            element_names[54]="Xe"; element_names[55]="Cs"; element_names[56]="Ba"; element_names[57]="La"; element_names[58]="Ce"; \
            element_names[59]="Pr"; element_names[60]="Nd"; element_names[61]="Pm"; element_names[62]="Sm"; element_names[63]="Eu"; \
            element_names[64]="Gd"; element_names[65]="Tb"; element_names[66]="Dy"; element_names[67]="Ho"; element_names[68]="Er"; \
            element_names[69]="Tm"; element_names[70]="Yb"; element_names[71]="Lu"; element_names[72]="Hf"; element_names[73]="Ta"; \
            element_names[74]="W"; element_names[75]="Re"; element_names[76]="Os"; element_names[77]="Ir"; element_names[78]="Pt"; \
            element_names[79]="Au"; element_names[80]="Hg"; element_names[81]="Tl"; element_names[82]="Pb"; element_names[83]="Bi"; \
            element_names[84]="Po"; element_names[85]="At"; element_names[86]="Rn"; element_names[87]="Fr"; element_names[88]="Ra"; \
            element_names[89]="Ac"; element_names[90]="Th"; element_names[91]="Pa"; element_names[92]="U"; element_names[93]="Np"; \
            element_names[94]="Pu"; element_names[95]="Am"; element_names[96]="Cm"; element_names[97]="Bk"; element_names[98]="Cf"; \
            element_names[99]="Es"; element_names[100]="Fm"; element_names[101]="Md"; element_names[102]="No"; element_names[103]="Lr"; \
            element_names[104]="Rf"; element_names[105]="Db"; element_names[106]="Sg"; element_names[107]="Bh"; element_names[108]="Hs"; \
            element_names[109]="Mt"; element_names[110]="Ds"; element_names[111]="Rg"; element_names[112]="Ch";}\
            {for(i=1;i<=112;i++)if($4==element_names[i])print i,$1,$2,$3,1,1,1;}' >>! atom.config
